FROM conda/miniconda3
MAINTAINER Victor Sande <https://github.com/victorsndvg>

RUN apt-get update \
    && apt-get -y upgrade \
    && apt-get install -y gosu \
    && apt-get install -y \
        wget curl git tar gzip bash python \
	vim nano emacs-nox bash-completion \
    && cd /tmp \
    && git clone https://github.com/girder/girder.git \
    && cd /tmp/girder \
    && cd clients/python \
    && pip install setuptools \
    && python setup.py sdist \
    && python setup.py install \
    && cd /tmp \
    && rm -rf /tmp/girder \
    && apt-get autoremove -y \
    && apt-get remove --purge -y wget curl git make 

# # TODO add user trick
# # SETUP ENV
# export LC_ALL=C.UTF-8
# export LANG=C.UTF-8


# Our helper scripts
COPY start-salome.sh /usr/local/bin/start.sh
# RUN perl -pi -e "s|||g" /usr/local/bin/start.sh

# Define user
USER feelpp
ENV HOME /home/feelpp 
WORKDIR $HOME

COPY WELCOME /etc/motd

# set alias
RUN echo "alias cp='cp -i'" > $HOME/.bash_aliases && \
    echo "alias egrep='egrep --color=auto'" >> $HOME/.bash_aliases && \
    echo "alias fgrep='fgrep --color=auto'" >> $HOME/.bash_aliases && \
    echo "alias grep='grep --color=auto'" >> $HOME/.bash_aliases && \
    echo "alias ls='ls --color=auto'" >> $HOME/.bash_aliases && \
    echo "alias mv='mv -i'" >> $HOME/.bash_aliases && \
    echo "alias rm='rm -i'" >> $HOME/.bash_aliases

# set OpenMP Threads
RUN echo "export OMP_NUM_THREADS=${NUMTHREADS}" >> $HOME/.bashrc

# OpenBLAS threads should be 1 to ensure performance
RUN echo "export OPENBLAS_NUM_THREADS=${NUMTHREADS}" >> $HOME/.bashrc && \
    echo "export OPENBLAS_VERBOSE=0" >> $HOME/.bashrc

 Add to bash
RUN echo "# Add completion for girder cli" >> $HOME/.bashrc && \
    echo "# see http://click.pocoo.org/6/bashcomplete/" >> $HOME/.bashrc && \
    echo "eval "$(_GIRDER_CLI_COMPLETE=source girder-cli)" >> $HOME/.bashrc

#see https://girder.readthedocs.io/en/latest/python-client.html

USER root
CMD ["/usr/local/bin/start.sh"]
